### ISSUE TITLE
meta tag og:image doesn't show up. 

### ISSUE THREAD

**Issue by xinghengwang** [mmistakes/minimal-mistakes#471]
- [ ] This is a question about using the theme.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:  3.2.13**  
- **`github-pages`** github-pages 
- **Operating system:** 

---

## Expected behavior

in `_config.yml`, I updated this line: 

`og_image                 : og_image.png`

Yet, in the resulting webblog page, I don't see the og:image meta tag anywhere. and facebook og debugger also complains that it doen't see the og:image meta tag. (the og_image.png file is already put into the images directory.)

I also tried to use full url like this also: 

`og_image                 : https://website.com/images/og_image.png`

it still doesn't work 
Can you explain if this is a bug or something I done wrong? 

Thanks

**Comment by mmistakes** [comment]
You're using an older version of the theme so it's entirely possible there was a bug that's since been fixed.  I recently merged a pull request related to `og_image` in fact, so I would suggest updating.

You probably only need to update [_includes/seo.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/seo.html) if you don't want to do a full theme update right now.

`og_image: filename.jpg    # placed in /images/` and `og_image: http://yourimage.com/filename.jpg` should both work.

Give the updated seo.html file a try and report back if the problem still exists.

**Comment by xinghengwang** [comment]
Yep. update the seo.html fixed the issue. Thanks!!!
