### ISSUE TITLE
Google Analytics cannot detect tracking code

### ISSUE THREAD

**Issue by weiyangtham** [mmistakes/minimal-mistakes#848]
- [x] This is a question about using the theme.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

I'm trying to set up Google Analytics but GA keeps telling me that it cannot find the tracking code.  I've tried a variety of things, including directly pasting the tracking code in `google-universal.html` but nothing seems to help. Any advice is much appreciated. This is the repo I'm having problems with [https://github.com/weiyangtham/weiyangtham.github.io](https://github.com/weiyangtham/weiyangtham.github.io)

**Comment by mmistakes** [comment]
Looks to me whatever edits you made to `_includes/analytics-providers/google-universal.html` broke things. You have invalid `{% if %}` statement wrapping the entire GA tracking script, which is why it's not appearing in your HTML source.

It should be this https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/analytics-providers/google-universal.html

```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '{{ site.analytics.google.tracking_id }}', 'auto');
  ga('send', 'pageview');
</script>
```

And then the YAML you have in your `_config.yml` should work.

**Comment by weiyangtham** [comment]
Thanks! I was having issues with the original script before I edited anything but this seems to have done the trick now
